### PR TITLE
tweaked some translations

### PR DESCRIPTION
**Pull request by JCGiron**
Made a few edits after proofreading the texts on the website.

### CODE REVIEW

**Comment by dshorthouse** [comment]
No problem @JCGiron. Looks like we might have had a small edit war on some of those periods on new lines – HAML doesn't like that, requiring the `succeed "." do` block of code.

**Comment by JCGiron** [comment]
Yes, I'm sorry. I've been more concerned with language correctness and concordance among files. Will try to be more careful.

**Comment by dshorthouse** [comment]
Oh, wasn't a criticism. What you've been doing is infinitely more important. I'm happy to convert those things because it's trivial in comparison. I was concerned *you* might have been frustrated with me swooping in afterward with a flurry of commits & then you having to pull-in new code all the time.

**Comment by JCGiron** [comment]
Oh! don't worry! This is helping me a lot with my GitHub and git commands skills!!

**Pull request merged**
